"""change enums pending status name to pending_payment

Revision ID: 134f2473f04d
Revises: 259f7595851c
Create Date: 2026-07-06 14:27:57.996501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134f2473f04d'
down_revision: Union[str, Sequence[str], None] = '259f7595851c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE orderstatus RENAME VALUE 'PENDING' TO 'PENDING_PAYMENT';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE orderstatus RENAME VALUE 'PENDING_PAYMENT' TO 'PENDING';"
    )
    # ### end Alembic commands ###

