"""change enums status paid->confirmed

Revision ID: 259f7595851c
Revises: 02d6aa408787
Create Date: 2026-06-19 22:10:57.041617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259f7595851c'
down_revision: Union[str, Sequence[str], None] = '02d6aa408787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE orderstatus RENAME VALUE 'PAID' TO 'CONFIRMED';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE orderstatus RENAME VALUE 'CONFIRMED' TO 'PAID';"
    )
    # ### end Alembic commands ###
