"""add failed payment status

Revision ID: 3b6a5e1ac33a
Revises: 7be88987d543
Create Date: 2026-07-07 13:17:11.941667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6a5e1ac33a'
down_revision: Union[str, Sequence[str], None] = '7be88987d543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE paymentstatus ADD VALUE 'FAILED';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
