"""change payments provider and provider_payment_id nullability to True

Revision ID: 6678990c636d
Revises: 3b6a5e1ac33a
Create Date: 2026-07-07 21:33:29.682035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6678990c636d'
down_revision: Union[str, Sequence[str], None] = '3b6a5e1ac33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'provider_payment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
